version: '3'

services:
  feature-flag:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ
      - MONGO_USER
      - MONGO_PASS
      - PORT
      - MONGO_HOST
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    restart: always
