version: '3'

services:
  mongodb:
    image: mongo:4.2.18
    environment:
      - TZ
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./flags_data:/data/db
    restart: always
