name: Prettier Workflow

on:
  workflow_call:

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
      - name: Install dependencies and run prettier check
        run: |
          npm install
          npm run format
